GET http://localhost:5000/country
###

###
GET http://localhost:5000/country/Armenia/2022/
###
GET http://localhost:5000/country/Armenia/2021/05
###
GET http://localhost:5000/country/Armenia

###create one

POST http://localhost:5000/country
Content-Type: application/json

{
   "name":"China",
    "imp_value":"100622,4716",
    "exp_value":"23840,33477",
    "date_":"2023/02/01",
    "year_":"2023",
    "month_":"02",
    "day_":"01"
}
###

GET http://localhost:5000/country/21
Content-Type: application/json

{
    "name":"germany",
    "imp_value":"100$",
    "exp_value":"200$",
    "date_":"27/04/2023",
    "year":"2023",
    "month":"04",
    "day":"27",

}


###

DELETE http://localhost:5000/Armenia
